version: '3.3'

services:
  php:
    image: php:8-fpm
    volumes:
      - ./php:/var/www/html
      - ${IMAGE_DIR}:/var/www/html/images
    networks:
      - app-network

  nginx:
    image: nginx:latest
    ports:
      - "16080:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./php:/var/www/html
      - ${IMAGE_DIR}:/var/www/html/images
    networks:
      - app-network
    depends_on:
      - php

  imgproxy:
    image: darthsim/imgproxy:latest
    ports:
      - 16081:8080
    environment:
      - IMGPROXY_KEY=${IMGPROXY_KEY}
      - IMGPROXY_SALT=${IMGPROXY_SALT}

networks:
  app-network:
    driver: bridge

